var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/employees/[id]/route.js")
R.c("server/chunks/src_lib_0d4x9ck._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/_0roqi21._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_employees_[id]_route_actions_0as6ul8.js")
R.m(45823)
module.exports=R.m(45823).exports
