var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/quality-observations/[id]/route.js")
R.c("server/chunks/src_12~5a9e._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/src_0aaee4_._.js")
R.c("server/chunks/src_lib_01gpzzc._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0urg5fn._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_quality-observations_[id]_route_actions_13eryf5.js")
R.m(20139)
module.exports=R.m(20139).exports
