var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reports/management/route.js")
R.c("server/chunks/src_lib_09osoz1._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_0z7jzy0._.js")
R.c("server/chunks/_0yi724r._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_lib_12z.r02._.js")
R.c("server/chunks/_next-internal_server_app_api_reports_management_route_actions_0fmhe49.js")
R.m(21928)
module.exports=R.m(21928).exports
