var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/employees/route.js")
R.c("server/chunks/src_lib_0.f1jfi._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0q9s7xg._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/_next-internal_server_app_api_employees_route_actions_0togsw0.js")
R.m(17519)
module.exports=R.m(17519).exports
