var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/dashboard/users/[id]/permissions/route.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_0z5y0be._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0clu~i.._.js")
R.c("server/chunks/0zjb_server_app_api_dashboard_users_[id]_permissions_route_actions_0exze8_.js")
R.m(46224)
module.exports=R.m(46224).exports
