var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reports/catalog/route.js")
R.c("server/chunks/src_lib_09osoz1._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_reports_0rvvkly._.js")
R.c("server/chunks/src_lib_0z7jzy0._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0pi81ld._.js")
R.c("server/chunks/_next-internal_server_app_api_reports_catalog_route_actions_0-puv9_.js")
R.m(46719)
module.exports=R.m(46719).exports
