var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/month-snapshots/[id]/route.js")
R.c("server/chunks/src_lib_09osoz1._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/_0jhx28a._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_month-snapshots_[id]_route_actions_108p2zf.js")
R.m(3672)
module.exports=R.m(3672).exports
