var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/employees/upload/route.js")
R.c("server/chunks/[root-of-the-server]__05qqwv3._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_11lew34._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/_next-internal_server_app_api_employees_upload_route_actions_0i0hdk8.js")
R.m(99751)
module.exports=R.m(99751).exports
