var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/quality/route.js")
R.c("server/chunks/_0jttsq5._.js")
R.c("server/chunks/src_0pa.k7t._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_0ozm8hj._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_lib_01gpzzc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_next-internal_server_app_api_quality_route_actions_0zdwc2v.js")
R.m(54821)
module.exports=R.m(54821).exports
