var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/activity-logs/route.js")
R.c("server/chunks/_11uek1j._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_activity-logs_route_actions_00bv-ry.js")
R.m(57196)
module.exports=R.m(57196).exports
