var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/hr-deductions/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_11ih34t._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_hr-deductions_route_actions_0kh51ae.js")
R.m(79549)
module.exports=R.m(79549).exports
