var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/biometric/clear/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0h~e743._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_biometric_clear_route_actions_07tl~oc.js")
R.m(8105)
module.exports=R.m(8105).exports
