var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/employee-documents/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0omdlok._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_employee-documents_[id]_route_actions_05npdp7.js")
R.m(66184)
module.exports=R.m(66184).exports
