var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/complaints/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/src_lib_01gpzzc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0_-093d._.js")
R.c("server/chunks/_next-internal_server_app_api_complaints_route_actions_0hswf5t.js")
R.m(15034)
module.exports=R.m(15034).exports
