var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/quality/[id]/reject/route.js")
R.c("server/chunks/src_0pa.k7t._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/_0yh6cl6._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_lib_01gpzzc._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_quality_[id]_reject_route_actions_0j3k28b.js")
R.m(71233)
module.exports=R.m(71233).exports
