var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/quality-migration/route.js")
R.c("server/chunks/[root-of-the-server]__05d8gdx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_09dbibf._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_quality-migration_route_actions_0ifkf_v.js")
R.m(65267)
module.exports=R.m(65267).exports
