var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/employee-documents/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0r0807f._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_employee-documents_route_actions_08blh.p.js")
R.m(77759)
module.exports=R.m(77759).exports
