var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/employee-360/[id]/route.js")
R.c("server/chunks/src_lib_091zglq._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/_0yg01h0._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/src_lib_06eeif.._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_employee-360_[id]_route_actions_0y2dhz1.js")
R.m(30911)
module.exports=R.m(30911).exports
