var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reports/capa/route.js")
R.c("server/chunks/_03y_tp1._.js")
R.c("server/chunks/src_lib_0bmnshk._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_reports_capa_route_actions_13tbv1e.js")
R.m(10475)
module.exports=R.m(10475).exports
