var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/repetition-alerts/route.js")
R.c("server/chunks/_056g5vn._.js")
R.c("server/chunks/src_lib_search_0nqld69._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_0pfeg~~._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_repetition-alerts_route_actions_0z5peap.js")
R.m(88827)
module.exports=R.m(88827).exports
