// src/components/layout/sidebar-icons.ts
// ══════════════════════════════════════════════════════════════
//  §SIDEBAR-WORKSPACE — shared sidebar icon registry.
//
//  The canonical navigation registry stores lucide icon NAMES (plain
//  strings); this map is the single name → component resolution for
//  BOTH sidebar surfaces (normal navigation and the edit workspace).
//  Pure data — no React state, safe to import from anywhere.
// ══════════════════════════════════════════════════════════════

import {
  LayoutDashboard,
  Users,
  Fingerprint,
  Clock,
  FileText,
  Scale,
  Award,
  Banknote,
  Plane,
  BarChart3,
  Settings,
  Database,
  ClipboardCheck,
  ShieldCheck,
  MessageSquareWarning,
  BookOpen,
  AlertTriangle,
  Monitor,
  Bell,
  Zap,
  Shield,
  Workflow,
  Eye,
  Tags,
  FilePlus2,
  Gauge,
  CalendarCog,
  Settings2,
  ScrollText,
  FileWarning,
  Network,
  FileBarChart,
  FileSearch,
  UserCircle,
  type LucideIcon,
} from 'lucide-react';

export const SIDEBAR_ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  Fingerprint,
  Clock,
  FileText,
  Scale,
  Award,
  Banknote,
  Plane,
  BarChart3,
  Settings,
  Database,
  ClipboardCheck,
  ShieldCheck,
  MessageSquareWarning,
  BookOpen,
  AlertTriangle,
  Monitor,
  Bell,
  Zap,
  Shield,
  Workflow,
  Eye,
  Tags,
  FilePlus2,
  Gauge,
  CalendarCog,
  Settings2,
  ScrollText,
  FileWarning,
  Network,
  FileBarChart,
  FileSearch,
  UserCircle,
};
