var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/organization/impact/route.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0rn-55z._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_organization_impact_route_actions_0p_kt-r.js")
R.m(73931)
module.exports=R.m(73931).exports
