var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/positions/[id]/route.js")
R.c("server/chunks/_0dlvcxx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__06-4wdz._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_positions_[id]_route_actions_0cpvdtt.js")
R.m(76501)
module.exports=R.m(76501).exports
