var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/quality/[id]/create-capa/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_00tta6.._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_quality_[id]_create-capa_route_actions_0-lhkh..js")
R.m(72337)
module.exports=R.m(72337).exports
