var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/organization/move/route.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0xbcknv._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_organization_move_route_actions_11lwjcw.js")
R.m(68680)
module.exports=R.m(68680).exports
