var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/kpi-reports/historical/route.js")
R.c("server/chunks/src_lib_09osoz1._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/src_lib_0z7jzy0._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0u9ie0t._.js")
R.c("server/chunks/_next-internal_server_app_api_kpi-reports_historical_route_actions_09th52b.js")
R.m(60111)
module.exports=R.m(60111).exports
