var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/kpi-reports/diagnose/route.js")
R.c("server/chunks/src_lib_09osoz1._.js")
R.c("server/chunks/src_lib_0.1nqhg._.js")
R.c("server/chunks/_07d8i5~._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_kpi-reports_diagnose_route_actions_05k5mkn.js")
R.m(5094)
module.exports=R.m(5094).exports
