var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/deduction-rules/seed/route.js")
R.c("server/chunks/_0o-6ilx._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__05d8gdx._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_attendance_0nv4mhv._.js")
R.c("server/chunks/_next-internal_server_app_api_deduction-rules_seed_route_actions_0lb7-rj.js")
R.m(75354)
module.exports=R.m(75354).exports
