var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/kpi-schemes/[id]/activate/route.js")
R.c("server/chunks/[root-of-the-server]__05d8gdx._.js")
R.c("server/chunks/_092qm6q._.js")
R.c("server/chunks/src_lib_0rcx3cp._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_kpi-schemes_[id]_activate_route_actions_0v4nlx7.js")
R.m(10657)
module.exports=R.m(10657).exports
