var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/performance-intelligence/route.js")
R.c("server/chunks/src_lib_0ne38to._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_09osoz1._.js")
R.c("server/chunks/src_lib_kpi-framework_0mzxenm._.js")
R.c("server/chunks/src_lib_0e8as9i._.js")
R.c("server/chunks/src_lib_0z7jzy0._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_lib_performance-intelligence_0ue7~hb._.js")
R.c("server/chunks/src_lib_attendance_0nv4mhv._.js")
R.c("server/chunks/_13gat.8._.js")
R.c("server/chunks/_next-internal_server_app_api_performance-intelligence_route_actions_06j~ar7.js")
R.m(91790)
module.exports=R.m(91790).exports
