var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/annual-snapshots/route.js")
R.c("server/chunks/_0y-j~-8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__0dzy71b._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_annual-snapshots_route_actions_0gp85qr.js")
R.m(90960)
module.exports=R.m(90960).exports
