var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/health/route.js")
R.c("server/chunks/src_lib_ai_0m1ws24._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__06-4wdz._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0wto4r5._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_health_route_actions_04ucc1l.js")
R.m(56056)
module.exports=R.m(56056).exports
