var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/attendance-kpi/[month]/route.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/_136nocf._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_attendance_0nv4mhv._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_attendance-kpi_[month]_route_actions_11q5y2g.js")
R.m(2540)
module.exports=R.m(2540).exports
