var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/evidence/preview/route.js")
R.c("server/chunks/src_lib_0t8z8s.._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/_0e-sc3-._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_next-internal_server_app_api_evidence_preview_route_actions_07.mz_d.js")
R.m(32673)
module.exports=R.m(32673).exports
