var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/biometric/upload/route.js")
R.c("server/chunks/[root-of-the-server]__08p4e21._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/_next-internal_server_app_api_biometric_upload_route_actions_0h33ub~.js")
R.m(32106)
module.exports=R.m(32106).exports
