var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reports/generate/route.js")
R.c("server/chunks/_11t9htg._.js")
R.c("server/chunks/src_lib_00lvp_7._.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_lib_attendance_0nv4mhv._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_reports_generate_route_actions_0s88bue.js")
R.m(49720)
module.exports=R.m(49720).exports
