var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/rules/seed-capa-templates/route.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0l2rd50._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_rules_seed-capa-templates_route_actions_0.2-~za.js")
R.m(28621)
module.exports=R.m(28621).exports
