var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/complaints/[id]/create-capa/route.js")
R.c("server/chunks/[root-of-the-server]__0api7p8._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0ngcure._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_complaints_[id]_create-capa_route_actions_0xuj4ku.js")
R.m(78008)
module.exports=R.m(78008).exports
