var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/quality-audit-log/route.js")
R.c("server/chunks/_0p.sb88._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/_next-internal_server_app_api_quality-audit-log_route_actions_029zbjx.js")
R.m(54566)
module.exports=R.m(54566).exports
