// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activity-logs/online/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity-logs/online">> = Specific
  const handler = {} as typeof import("../../src/app/api/activity-logs/online/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activity-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/activity-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/diagnostics">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/models">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/provider-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/provider-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/provider-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/quality-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/quality-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/quality-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/employee-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/employee-performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/employee-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/annual-snapshots/[year]/close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/annual-snapshots/[year]/close">> = Specific
  const handler = {} as typeof import("../../src/app/api/annual-snapshots/[year]/close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/annual-snapshots/[year]/reopen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/annual-snapshots/[year]/reopen">> = Specific
  const handler = {} as typeof import("../../src/app/api/annual-snapshots/[year]/reopen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/annual-snapshots/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/annual-snapshots/compare">> = Specific
  const handler = {} as typeof import("../../src/app/api/annual-snapshots/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/annual-snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/annual-snapshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/annual-snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance-kpi/[month]/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance-kpi/[month]/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance-kpi/[month]/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance-kpi/[month]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance-kpi/[month]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance-kpi/[month]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance-results/[month]/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance-results/[month]/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance-results/[month]/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance-results/[month]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance-results/[month]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance-results/[month]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance-results/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance-results/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance-results/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/biometric/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/biometric/clear">> = Specific
  const handler = {} as typeof import("../../src/app/api/biometric/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/biometric/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/biometric">> = Specific
  const handler = {} as typeof import("../../src/app/api/biometric/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/biometric/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/biometric/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/biometric/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/capa-cases/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capa-cases/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/capa-cases/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/capa-cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capa-cases">> = Specific
  const handler = {} as typeof import("../../src/app/api/capa-cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/capa-sla/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capa-sla">> = Specific
  const handler = {} as typeof import("../../src/app/api/capa-sla/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/complaints/[id]/create-capa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/complaints/[id]/create-capa">> = Specific
  const handler = {} as typeof import("../../src/app/api/complaints/[id]/create-capa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/complaints/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/complaints/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/complaints/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/complaints/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/api/complaints/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/capa-sla-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/capa-sla-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/capa-sla-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/users/[id]/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/users/[id]/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/users/[id]/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/users/[id]/photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/users/[id]/photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/users/[id]/photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/deduction-rules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deduction-rules/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/deduction-rules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/deduction-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deduction-rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/deduction-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/deduction-rules/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deduction-rules/seed">> = Specific
  const handler = {} as typeof import("../../src/app/api/deduction-rules/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employee-360/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employee-360/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employee-360/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employee-documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employee-documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employee-documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employee-documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employee-documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/employee-documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employee-performance/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employee-performance/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employee-performance/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/org-nodes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/org-nodes">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/org-nodes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/evidence/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/evidence/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/firebase/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/firebase/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/firebase/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/follow-ups/[id]/escalate-capa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow-ups/[id]/escalate-capa">> = Specific
  const handler = {} as typeof import("../../src/app/api/follow-ups/[id]/escalate-capa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/follow-ups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow-ups/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/follow-ups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/follow-ups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow-ups">> = Specific
  const handler = {} as typeof import("../../src/app/api/follow-ups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/home/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/home/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hr-deductions/[id]/create-capa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hr-deductions/[id]/create-capa">> = Specific
  const handler = {} as typeof import("../../src/app/api/hr-deductions/[id]/create-capa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hr-deductions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hr-deductions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/hr-deductions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hr-deductions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hr-deductions">> = Specific
  const handler = {} as typeof import("../../src/app/api/hr-deductions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hr-performance/[month]/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hr-performance/[month]/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/hr-performance/[month]/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/knowledge-base/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge-base/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/knowledge-base/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/knowledge-base/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge-base">> = Specific
  const handler = {} as typeof import("../../src/app/api/knowledge-base/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-framework/employee-result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-framework/employee-result">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-framework/employee-result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-framework/employee-scheme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-framework/employee-scheme">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-framework/employee-scheme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-reports/diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-reports/diagnose">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-reports/diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-reports/employee/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-reports/employee">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-reports/employee/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-reports/historical/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-reports/historical">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-reports/historical/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-reports/monthly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-reports/monthly">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-reports/monthly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-reports/mtd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-reports/mtd">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-reports/mtd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-reports/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-reports/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-reports/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-schemes/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-schemes/[id]/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-schemes/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-schemes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-schemes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-schemes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-schemes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-schemes">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-schemes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpi-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpi-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpi-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/month-snapshots/[id]/close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/month-snapshots/[id]/close">> = Specific
  const handler = {} as typeof import("../../src/app/api/month-snapshots/[id]/close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/month-snapshots/[id]/reopen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/month-snapshots/[id]/reopen">> = Specific
  const handler = {} as typeof import("../../src/app/api/month-snapshots/[id]/reopen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/month-snapshots/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/month-snapshots/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/month-snapshots/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/month-snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/month-snapshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/month-snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notification-stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification-stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/notification-stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/mark-all-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/mark-all-read">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/mark-all-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/observation-categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observation-categories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/observation-categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/observation-categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observation-categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/observation-categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/observation-templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observation-templates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/observation-templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/observation-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observation-templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/observation-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organization/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/organization/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organization/employees/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/employees/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/organization/employees/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organization/impact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/impact">> = Specific
  const handler = {} as typeof import("../../src/app/api/organization/impact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organization/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/organization/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization">> = Specific
  const handler = {} as typeof import("../../src/app/api/organization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance-intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance-intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance-intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/positions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/positions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/positions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/positions">> = Specific
  const handler = {} as typeof import("../../src/app/api/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-audit-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-audit-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-migration/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-migration">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-migration/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-observations/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-observations/[id]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-observations/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-observations/[id]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-observations/[id]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-observations/[id]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-observations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-observations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-observations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-observations/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-observations/migrate">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-observations/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality-observations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-observations">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality-observations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality/[id]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality/[id]/create-capa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality/[id]/create-capa">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality/[id]/create-capa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality/[id]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality/[id]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality/[id]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quality/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/quality/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repetition-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repetition-alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/repetition-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/capa-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/capa-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/capa-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/capa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/capa">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/capa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/employee-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/employee-detail">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/employee-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/filter-options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/filter-options">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/filter-options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/hr-performance/decision/employee/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/hr-performance/decision/employee">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/hr-performance/decision/employee/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/hr-performance/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/hr-performance/decision">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/hr-performance/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/hr-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/hr-performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/hr-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/management/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/management">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/management/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/waive-deduction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/waive-deduction">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/waive-deduction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requests/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/risk-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk-center">> = Specific
  const handler = {} as typeof import("../../src/app/api/risk-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rule-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rule-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/rule-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/rules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rules/execute-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules/execute-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/rules/execute-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rules/execute/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules/execute/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/rules/execute/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rules/seed-capa-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules/seed-capa-templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/rules/seed-capa-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rules/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rules/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/rules/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/travel/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/travel/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/travel/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/travel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/travel">> = Specific
  const handler = {} as typeof import("../../src/app/api/travel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/travel/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/travel/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/travel/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/unseen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unseen">> = Specific
  const handler = {} as typeof import("../../src/app/api/unseen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user-preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user-preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/user-preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
