var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/risk-center/route.js")
R.c("server/chunks/[root-of-the-server]__098igru._.js")
R.c("server/chunks/src_lib_0yqkn.1._.js")
R.c("server/chunks/src_lib_079aun4._.js")
R.c("server/chunks/_0b57xqx._.js")
R.c("server/chunks/[root-of-the-server]__0vxxedz._.js")
R.c("server/chunks/src_03zg4r8._.js")
R.c("server/chunks/_0riam5.._.js")
R.c("server/chunks/_0-2dxey._.js")
R.c("server/chunks/_next-internal_server_app_api_risk-center_route_actions_03k1wvh.js")
R.m(96662)
module.exports=R.m(96662).exports
